# Generated by Django 3.2.6 on 2021-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210822_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='idealfor',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='necktype',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sleeve',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
